
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  twoFAEnabled: 'twoFAEnabled',
  twoFASecret: 'twoFASecret',
  verified: 'verified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.SiteSettingsScalarFieldEnum = {
  id: 'id',
  heroTitle: 'heroTitle',
  heroTagline: 'heroTagline',
  heroSubtext: 'heroSubtext',
  heroVideoUrl: 'heroVideoUrl',
  heroCategories: 'heroCategories',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  contactAddress: 'contactAddress',
  googleMapUrl: 'googleMapUrl',
  webhookUrl: 'webhookUrl',
  footerLinks: 'footerLinks',
  socialLinks: 'socialLinks',
  copyrightText: 'copyrightText',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  coverImage: 'coverImage',
  description: 'description',
  shortCode: 'shortCode',
  sequenceNumber: 'sequenceNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  logoUrl: 'logoUrl',
  bannerUrl: 'bannerUrl',
  description: 'description',
  shortCode: 'shortCode',
  sequenceNumber: 'sequenceNumber',
  catalogPdfUrl: 'catalogPdfUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  description: 'description',
  category: 'category',
  client: 'client',
  clientId: 'clientId',
  projectCode: 'projectCode',
  sequenceNumber: 'sequenceNumber',
  videoUrl: 'videoUrl',
  imageUrl: 'imageUrl',
  gallery: 'gallery',
  brandDetails: 'brandDetails',
  featured: 'featured',
  pdfUrl: 'pdfUrl',
  status: 'status',
  budget: 'budget',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  slNo: 'slNo',
  name: 'name',
  brand: 'brand',
  category: 'category',
  subcategory: 'subcategory',
  shortCode: 'shortCode',
  width: 'width',
  height: 'height',
  depth: 'depth',
  measurementType: 'measurementType',
  thickness: 'thickness',
  finish: 'finish',
  description: 'description',
  tags: 'tags',
  imageUrl: 'imageUrl',
  galleryImages: 'galleryImages',
  catalogPdfUrl: 'catalogPdfUrl',
  qtyInStock: 'qtyInStock',
  price: 'price',
  finishOptions: 'finishOptions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  name: 'name',
  designation: 'designation',
  category: 'category',
  memberCode: 'memberCode',
  photoUrl: 'photoUrl',
  phone: 'phone',
  bio: 'bio',
  linkedin: 'linkedin',
  instagram: 'instagram',
  sequenceNumber: 'sequenceNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoadmapStepScalarFieldEnum = {
  id: 'id',
  stepNumber: 'stepNumber',
  title: 'title',
  description: 'description',
  year: 'year',
  createdAt: 'createdAt'
};

exports.Prisma.InquiryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  type: 'type',
  subject: 'subject',
  message: 'message',
  productOrBrand: 'productOrBrand',
  createdAt: 'createdAt'
};

exports.Prisma.ServiceScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  icon: 'icon',
  imageUrl: 'imageUrl',
  category: 'category',
  buttonText: 'buttonText',
  buttonLink: 'buttonLink',
  seoUrl: 'seoUrl',
  sequenceNumber: 'sequenceNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TestimonialScalarFieldEnum = {
  id: 'id',
  clientName: 'clientName',
  company: 'company',
  rating: 'rating',
  review: 'review',
  clientImage: 'clientImage',
  sequenceNumber: 'sequenceNumber',
  createdAt: 'createdAt'
};

exports.Prisma.BlogScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  category: 'category',
  tags: 'tags',
  content: 'content',
  featuredImage: 'featuredImage',
  author: 'author',
  publishDate: 'publishDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MediaItemScalarFieldEnum = {
  id: 'id',
  fileName: 'fileName',
  fileUrl: 'fileUrl',
  fileType: 'fileType',
  folder: 'folder',
  altText: 'altText',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.TaxonomyScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  code: 'code',
  sequenceNumber: 'sequenceNumber',
  createdAt: 'createdAt'
};

exports.Prisma.NavMenuItemScalarFieldEnum = {
  id: 'id',
  label: 'label',
  href: 'href',
  sequenceNumber: 'sequenceNumber',
  isExternal: 'isExternal',
  createdAt: 'createdAt'
};

exports.Prisma.SeoConfigScalarFieldEnum = {
  id: 'id',
  pageSlug: 'pageSlug',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  keywords: 'keywords',
  ogImage: 'ogImage',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  user: 'user',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.ProjectItemScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  productId: 'productId',
  productName: 'productName',
  brand: 'brand',
  category: 'category',
  finish: 'finish',
  dimensions: 'dimensions',
  quantity: 'quantity',
  notes: 'notes'
};

exports.Prisma.FAQScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  category: 'category',
  order: 'order',
  createdAt: 'createdAt'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  company: 'company',
  address: 'address',
  logoUrl: 'logoUrl',
  industry: 'industry',
  passwordHash: 'passwordHash',
  accessCode: 'accessCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScheduleItemScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  room: 'room',
  category: 'category',
  supplier: 'supplier',
  tradePrice: 'tradePrice',
  clientPrice: 'clientPrice',
  price: 'price',
  status: 'status',
  imageUrl: 'imageUrl',
  specs: 'specs',
  dimensions: 'dimensions',
  quantity: 'quantity',
  unit: 'unit',
  approvedAt: 'approvedAt',
  approvedBy: 'approvedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScheduleCommentScalarFieldEnum = {
  id: 'id',
  scheduleItemId: 'scheduleItemId',
  authorName: 'authorName',
  authorEmail: 'authorEmail',
  authorRole: 'authorRole',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.ProjectDocumentScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  clientId: 'clientId',
  name: 'name',
  fileUrl: 'fileUrl',
  fileType: 'fileType',
  fileSize: 'fileSize',
  uploadedBy: 'uploadedBy',
  createdAt: 'createdAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  projectId: 'projectId',
  clientId: 'clientId',
  title: 'title',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  dueDate: 'dueDate',
  stripePaymentLink: 'stripePaymentLink',
  stripeSessionId: 'stripeSessionId',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CareerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  department: 'department',
  location: 'location',
  description: 'description',
  requirements: 'requirements',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.ApplicationScalarFieldEnum = {
  id: 'id',
  careerId: 'careerId',
  name: 'name',
  email: 'email',
  resumeUrl: 'resumeUrl',
  portfolioUrl: 'portfolioUrl',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.ContactMessageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  subject: 'subject',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.SEODataScalarFieldEnum = {
  id: 'id',
  page: 'page',
  title: 'title',
  description: 'description',
  keywords: 'keywords',
  ogImage: 'ogImage',
  updatedAt: 'updatedAt'
};

exports.Prisma.SettingsScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  email: 'email',
  phone: 'phone',
  address: 'address',
  facebook: 'facebook',
  twitter: 'twitter',
  instagram: 'instagram',
  linkedin: 'linkedin',
  whatsapp: 'whatsapp',
  updatedAt: 'updatedAt'
};

exports.Prisma.BlogPostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  content: 'content',
  summary: 'summary',
  imageUrl: 'imageUrl',
  category: 'category',
  authorId: 'authorId',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  blogPostId: 'blogPostId',
  authorName: 'authorName',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ScheduleStatus = exports.$Enums.ScheduleStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  REJECTED: 'REJECTED'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  VOID: 'VOID'
};

exports.Prisma.ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  SiteSettings: 'SiteSettings',
  Category: 'Category',
  Brand: 'Brand',
  Project: 'Project',
  Product: 'Product',
  TeamMember: 'TeamMember',
  RoadmapStep: 'RoadmapStep',
  Inquiry: 'Inquiry',
  Service: 'Service',
  Testimonial: 'Testimonial',
  Blog: 'Blog',
  MediaItem: 'MediaItem',
  Taxonomy: 'Taxonomy',
  NavMenuItem: 'NavMenuItem',
  SeoConfig: 'SeoConfig',
  ActivityLog: 'ActivityLog',
  ProjectItem: 'ProjectItem',
  FAQ: 'FAQ',
  Client: 'Client',
  ScheduleItem: 'ScheduleItem',
  ScheduleComment: 'ScheduleComment',
  ProjectDocument: 'ProjectDocument',
  Invoice: 'Invoice',
  Career: 'Career',
  Application: 'Application',
  ContactMessage: 'ContactMessage',
  SEOData: 'SEOData',
  Settings: 'Settings',
  BlogPost: 'BlogPost',
  Tag: 'Tag',
  Comment: 'Comment'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
